import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
 <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DEX Crypto</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>DEX Crypto</h1>
        <nav>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#">Trade</a></li>
                <li><a href="#">Wallet</a></li>
                <li><a href="#">Settings</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <section id="trade-section">
            <h2>Trade</h2>
            <!-- Trade form and market information go here -->
        </section>

        <section id="wallet-section">
            <h2>Wallet</h2>
            <!-- Wallet balance and transaction history go here -->
        </section>
    </main>

    <footer>
        <p>&copy; 2024 DEX Crypto. All rights reserved.</p>
    </footer>

    <script src="app.js"></script>
</body>
</html>
  );
}
